#!/bin/sh
args=$@
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
echo $XAUTH
echo $XSOCK
echo "docker run --privileged=true -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -v /dev/dri:/dev/dri:rw -e DISPLAY=$DISPLAY -e XAUTHORITY=$XAUTH $args"

docker run --privileged=true -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -v /dev/dri:/dev/dri:rw -e DISPLAY=$DISPLAY -e XAUTHORITY=$XAUTH $args

